create table cards
(
    card_id       bigint generated by default as identity,
    difficulty    varchar(255) check (difficulty in ('easy', 'normal', 'hard')),
    foreign_word  varchar(255),
    korean_word   varchar(255),
    language_code varchar(255) check (language_code in
                                      ('en', 'ja', 'ar', 'pt', 'zh', 'cs', 'da', 'de', 'fr', 'vi', 'es')),
    meaning_group varchar(255) check (meaning_group in ('Something', 'anything')),
    primary key (card_id)
);
create table user_cards (
                            user_card_id bigint generated by default as identity,
                            card_id bigint,
                            user_deck_id bigint,
                            next_study_date TIMESTAMP DEFAULT now(),
                            score integer,
                            primary key (user_card_id)
);
create table user_decks (
                            user_deck_id bigint generated by default as identity,
                            difficulty varchar(255) check (difficulty in ('easy', 'normal', 'hard')),
                            language_code varchar(255) check (language_code in
                                                              ('en', 'ja', 'ar', 'pt', 'zh', 'cs', 'da', 'de', 'fr', 'vi', 'es')),
                            user_id bigint,
                            primary key (user_deck_id)
);
create table users (
                       user_id bigint generated by default as identity,
                       today_review_words integer,
                       today_study_words integer,
                       primary key (user_id)
);
alter table if exists user_cards
    add constraint FK6c88junkes22vgqua5kyc543e
    foreign key (card_id)
    references cards;
alter table if exists user_cards
    add constraint FKo8aeti9to59mjchpxomdtj66n
    foreign key (user_deck_id)
    references user_decks;
alter table if exists user_decks
    add constraint FK8ltdfcae88jxudtpojb005g9h
    foreign key (user_id)
    references users;

INSERT INTO cards(korean_word, foreign_word, language_code, difficulty)
VALUES
    -- en, easy
    ('가족', 'Family', 'en', 'easy'),
    ('학교', 'School', 'en', 'easy'),
    ('친구', 'Friend', 'en', 'easy'),
    ('사과', 'Apple', 'en', 'easy'),
    ('의사', 'Doctor', 'en', 'easy'),
    ('도서관', 'Library', 'en', 'easy'),
    ('컴퓨터', 'Computer', 'en', 'easy'),
    ('전화', 'Phone', 'en', 'easy'),
    ('비행기', 'Airplane', 'en', 'easy'),
    ('기차', 'Train', 'en', 'easy'),
    ('자동차', 'Car', 'en', 'easy'),
    ('집', 'House', 'en', 'easy'),
    ('강아지', 'Puppy', 'en', 'easy'),
    ('고양이', 'Cat', 'en', 'easy'),
    ('음악', 'Music', 'en', 'easy'),
    ('영화', 'Movie', 'en', 'easy'),
    ('책', 'Book', 'en', 'easy'),
    ('공원', 'Park', 'en', 'easy'),
    ('해변', 'Beach', 'en', 'easy'),
    ('가게', 'Store', 'en', 'easy'),

    -- en, normal
    ('별빛', 'Starlight', 'en', 'normal'),
    ('희망', 'Hope', 'en', 'normal'),
    ('자유', 'Freedom', 'en', 'normal'),
    ('행운', 'Luck', 'en', 'normal'),
    ('평화', 'Peace', 'en', 'normal'),
    ('용기', 'Courage', 'en', 'normal'),
    ('조화', 'Harmony', 'en', 'normal'),
    ('열정', 'Passion', 'en', 'normal'),
    ('우정', 'Friendship', 'en', 'normal'),
    ('모험', 'Adventure', 'en', 'normal'),
    ('지혜', 'Wisdom', 'en', 'normal'),
    ('믿음', 'Faith', 'en', 'normal'),
    ('사상', 'Ideology', 'en', 'normal'),
    ('역사', 'History', 'en', 'normal'),
    ('문화', 'Culture', 'en', 'normal'),
    ('철학', 'Philosophy', 'en', 'normal'),
    ('예술', 'Art', 'en', 'normal'),
    ('공상', 'Imagination', 'en', 'normal'),
    ('기억', 'Memory', 'en', 'normal'),

    -- en, hard
    ('지속', 'Persistence', 'en', 'hard'),
    ('헌신', 'Dedication', 'en', 'hard'),
    ('영감', 'Inspiration', 'en', 'hard'),
    ('탄생', 'Genesis', 'en', 'hard'),
    ('연민', 'Compassion', 'en', 'hard'),
    ('동경', 'Aspiration', 'en', 'hard'),
    ('고요함', 'Serenity', 'en', 'hard'),
    ('통찰', 'Insight', 'en', 'hard'),
    ('감사', 'Gratitude', 'en', 'hard'),
    ('협력', 'Collaboration', 'en', 'hard'),
    ('중재', 'Mediation', 'en', 'hard'),
    ('통합', 'Integration', 'en', 'hard'),
    ('속도', 'Velocity', 'en', 'hard'),
    ('권위', 'Authority', 'en', 'hard'),
    ('소유', 'Possession', 'en', 'hard'),
    ('표현', 'Expression', 'en', 'hard'),
    ('절제', 'Moderation', 'en', 'hard'),
    ('대의', 'Cause', 'en', 'hard'),
    ('주제', 'Theme', 'en', 'hard'),
-- Easy difficulty entries
    ('안녕하세요', 'こんにちは', 'ja', 'easy'),
    ('사랑', '愛', 'ja', 'easy'),
    ('행복', '幸せ', 'ja', 'easy'),
    ('친구', '友達', 'ja', 'easy'),
    ('학교', '学校', 'ja', 'easy'),
    ('책', '本', 'ja', 'easy'),
    ('물', '水', 'ja', 'easy'),
    ('집', '家', 'ja', 'easy'),
    ('자동차', '車', 'ja', 'easy'),
    ('음악', '音楽', 'ja', 'easy'),
    ('커피', 'コーヒー', 'ja', 'easy'),
    ('밥', 'ご飯', 'ja', 'easy'),
    ('영화', '映画', 'ja', 'easy'),
    ('하늘', '空', 'ja', 'easy'),
    ('바다', '海', 'ja', 'easy'),
    ('아침', '朝', 'ja', 'easy'),
    ('저녁', '夕方', 'ja', 'easy'),
    ('봄', '春', 'ja', 'easy'),
    ('여름', '夏', 'ja', 'easy'),
    ('겨울', '冬', 'ja', 'easy'),

-- Normal difficulty entries
    ('문학', '文学', 'ja', 'normal'),
    ('자유', '自由', 'ja', 'normal'),
    ('예술', '芸術', 'ja', 'normal'),
    ('철학', '哲学', 'ja', 'normal'),
    ('역사', '歴史', 'ja', 'normal'),
    ('과학', '科学', 'ja', 'normal'),
    ('기술', '技術', 'ja', 'normal'),
    ('경제', '経済', 'ja', 'normal'),
    ('정치', '政治', 'ja', 'normal'),
    ('문화', '文化', 'ja', 'normal'),
    ('사회', '社会', 'ja', 'normal'),
    ('종교', '宗教', 'ja', 'normal'),
    ('가족', '家族', 'ja', 'normal'),
    ('친절', '親切', 'ja', 'normal'),
    ('여행', '旅行', 'ja', 'normal'),
    ('도서관', '図書館', 'ja', 'normal'),
    ('음식', '食べ物', 'ja', 'normal'),
    ('공원', '公園', 'ja', 'normal'),
    ('운동', '運動', 'ja', 'normal'),
    ('건강', '健康', 'ja', 'normal'),

-- Hard difficulty entries
    ('복잡성', '複雑さ', 'ja', 'hard'),
    ('미학', '美学', 'ja', 'hard'),
    ('추상적', '抽象的', 'ja', 'hard'),
    ('심리학', '心理学', 'ja', 'hard'),
    ('의식', '意識', 'ja', 'hard'),
    ('현실', '現実', 'ja', 'hard'),
    ('초현실', '超現実', 'ja', 'hard'),
    ('정신', '精神', 'ja', 'hard'),
    ('윤리', '倫理', 'ja', 'hard'),
    ('문명', '文明', 'ja', 'hard'),
    ('이론', '理論', 'ja', 'hard'),
    ('방법론', '方法論', 'ja', 'hard'),
    ('철학적', '哲学的', 'ja', 'hard'),
    ('감각', '感覚', 'ja', 'hard'),
    ('인지', '認知', 'ja', 'hard'),
    ('분석', '分析', 'ja', 'hard'),
    ('통찰력', '洞察力', 'ja', 'hard'),
    ('객관성', '客観性', 'ja', 'hard'),
    ('주관성', '主観性', 'ja', 'hard'),
    ('합리성', '合理性', 'ja', 'hard');
;

insert into users(user_id) values (1);

BEGIN;

WITH inserted_deck AS (
INSERT INTO user_decks(user_id, language_code, difficulty)
VALUES (1, 'en', 'normal')
    RETURNING user_deck_id)
INSERT INTO user_cards(card_id, user_deck_id)
SELECT cards.card_id, inserted_deck.user_deck_id
FROM cards, inserted_deck
WHERE cards.language_code = 'en' AND cards.difficulty = 'normal';

WITH inserted_deck AS (
INSERT INTO user_decks(user_id, language_code, difficulty)
VALUES (1, 'en', 'hard')
    RETURNING user_deck_id)
INSERT INTO user_cards(card_id, user_deck_id)
SELECT cards.card_id, inserted_deck.user_deck_id
FROM cards, inserted_deck
WHERE cards.language_code = 'en' AND cards.difficulty = 'hard';

COMMIT;
