openapi: 3.0.1
info:
  title: Anki
  description: Anki 작업
  version: 1.0.0
servers:
- url: http://localhost:8080/
tags: []
paths:
  /cards/{id}:
    get:
      tags:
      - StudyCards
      summary: userCard 보기
      description: userCard 보기
      operationId: user-card-controller-test/get-user-cards
      parameters:
      - name: id
        in: path
        description: userCard 고유번호
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/cards-id-211271039"
              examples:
                user-card-controller-test/get-user-cards:
                  value: "{\"cardId\":1,\"koreanWord\":\"가족\",\"foreignWord\":\"Family\"\
                    ,\"difficulty\":\"easy\",\"languageCode\":\"en\",\"userCardId\"\
                    :1,\"score\":null,\"nextStudyDate\":\"2024-12-24T15:12:10.478841\"\
                    ,\"lapses\":5,\"lastReview\":\"2024-12-24T15:12:10.478841\",\"\
                    reps\":72,\"scheduledDays\":0.9,\"stability\":1.3,\"state\":\"\
                    Review\"}"
    post:
      tags:
      - StudyCards
      summary: Card 학습결과를 갱신
      description: Card 학습결과를 갱신
      operationId: user-card-controller-test/put-user-cards
      parameters:
      - name: id
        in: path
        description: userCard 고유번호
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/cards-id-1143663180"
            examples:
              user-card-controller-test/put-user-cards:
                value: "{\"lapses\":5,\"reps\":72,\"scheduledDays\":0.9,\"nextStudyDate\"\
                  :\"2024-12-24T15:12:10.4788412\",\"lastReview\":\"2024-12-24T15:12:10.4788412\"\
                  ,\"state\":\"Review\",\"stability\":1.3}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/cards-id-211271039"
              examples:
                user-card-controller-test/put-user-cards:
                  value: "{\"cardId\":1,\"koreanWord\":\"가족\",\"foreignWord\":\"Family\"\
                    ,\"difficulty\":\"easy\",\"languageCode\":\"en\",\"userCardId\"\
                    :1,\"score\":null,\"nextStudyDate\":\"2024-12-24T15:12:10.4788412\"\
                    ,\"lapses\":5,\"lastReview\":\"2024-12-24T15:12:10.4788412\",\"\
                    reps\":72,\"scheduledDays\":0.9,\"stability\":1.3,\"state\":\"\
                    Review\"}"
  /decks:
    get:
      tags:
      - Decks
      summary: 검색어 조건에 맞는 Deck 보기
      description: 검색어 조건에 맞는 Deck 보기
      operationId: deck-controller-test/get-decks
      parameters:
      - name: queryType
        in: query
        description: 의미에 따른 분류인가 / 난이도에 따른 분류인가
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/decks"
              examples:
                deck-controller-test/get-decks:
                  value: "{\"size\":6,\"content\":[{\"category\":\"easy\",\"languageCode\"\
                    :\"en\",\"cardCounts\":20},{\"category\":\"normal\",\"languageCode\"\
                    :\"en\",\"cardCounts\":19},{\"category\":\"easy\",\"languageCode\"\
                    :\"ja\",\"cardCounts\":20},{\"category\":\"hard\",\"languageCode\"\
                    :\"en\",\"cardCounts\":19},{\"category\":\"normal\",\"languageCode\"\
                    :\"ja\",\"cardCounts\":20},{\"category\":\"hard\",\"languageCode\"\
                    :\"ja\",\"cardCounts\":20}]}"
  /decks/cards:
    get:
      tags:
      - Decks
      summary: 덱에 포함된 카드 모음
      description: 덱에 포함된 카드 모음
      operationId: deck-controller-test/get-decks-card
      parameters:
      - name: queryType
        in: query
        description: 의미에 따른 분류인가 / 난이도에 따른 분류인가
        required: true
        schema:
          type: string
      - name: query
        in: query
        description: 검색어 (difficulty 또는 meaningGroup)
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/cards"
              examples:
                deck-controller-test/get-decks-card:
                  value: "{\"page\":0,\"pageSize\":1,\"size\":20,\"content\":[{\"\
                    cardId\":1,\"koreanWord\":\"가족\",\"foreignWord\":\"Family\",\"\
                    difficulty\":\"easy\",\"languageCode\":\"en\"},{\"cardId\":2,\"\
                    koreanWord\":\"학교\",\"foreignWord\":\"School\",\"difficulty\"\
                    :\"easy\",\"languageCode\":\"en\"},{\"cardId\":3,\"koreanWord\"\
                    :\"친구\",\"foreignWord\":\"Friend\",\"difficulty\":\"easy\",\"\
                    languageCode\":\"en\"},{\"cardId\":4,\"koreanWord\":\"사과\",\"\
                    foreignWord\":\"Apple\",\"difficulty\":\"easy\",\"languageCode\"\
                    :\"en\"},{\"cardId\":5,\"koreanWord\":\"의사\",\"foreignWord\":\"\
                    Doctor\",\"difficulty\":\"easy\",\"languageCode\":\"en\"},{\"\
                    cardId\":6,\"koreanWord\":\"도서관\",\"foreignWord\":\"Library\"\
                    ,\"difficulty\":\"easy\",\"languageCode\":\"en\"},{\"cardId\"\
                    :7,\"koreanWord\":\"컴퓨터\",\"foreignWord\":\"Computer\",\"difficulty\"\
                    :\"easy\",\"languageCode\":\"en\"},{\"cardId\":8,\"koreanWord\"\
                    :\"전화\",\"foreignWord\":\"Phone\",\"difficulty\":\"easy\",\"languageCode\"\
                    :\"en\"},{\"cardId\":9,\"koreanWord\":\"비행기\",\"foreignWord\"\
                    :\"Airplane\",\"difficulty\":\"easy\",\"languageCode\":\"en\"\
                    },{\"cardId\":10,\"koreanWord\":\"기차\",\"foreignWord\":\"Train\"\
                    ,\"difficulty\":\"easy\",\"languageCode\":\"en\"},{\"cardId\"\
                    :11,\"koreanWord\":\"자동차\",\"foreignWord\":\"Car\",\"difficulty\"\
                    :\"easy\",\"languageCode\":\"en\"},{\"cardId\":12,\"koreanWord\"\
                    :\"집\",\"foreignWord\":\"House\",\"difficulty\":\"easy\",\"languageCode\"\
                    :\"en\"},{\"cardId\":13,\"koreanWord\":\"강아지\",\"foreignWord\"\
                    :\"Puppy\",\"difficulty\":\"easy\",\"languageCode\":\"en\"},{\"\
                    cardId\":14,\"koreanWord\":\"고양이\",\"foreignWord\":\"Cat\",\"\
                    difficulty\":\"easy\",\"languageCode\":\"en\"},{\"cardId\":15,\"\
                    koreanWord\":\"음악\",\"foreignWord\":\"Music\",\"difficulty\":\"\
                    easy\",\"languageCode\":\"en\"},{\"cardId\":16,\"koreanWord\"\
                    :\"영화\",\"foreignWord\":\"Movie\",\"difficulty\":\"easy\",\"languageCode\"\
                    :\"en\"},{\"cardId\":17,\"koreanWord\":\"책\",\"foreignWord\":\"\
                    Book\",\"difficulty\":\"easy\",\"languageCode\":\"en\"},{\"cardId\"\
                    :18,\"koreanWord\":\"공원\",\"foreignWord\":\"Park\",\"difficulty\"\
                    :\"easy\",\"languageCode\":\"en\"},{\"cardId\":19,\"koreanWord\"\
                    :\"해변\",\"foreignWord\":\"Beach\",\"difficulty\":\"easy\",\"languageCode\"\
                    :\"en\"},{\"cardId\":20,\"koreanWord\":\"가게\",\"foreignWord\"\
                    :\"Store\",\"difficulty\":\"easy\",\"languageCode\":\"en\"}]}"
  /user/option:
    post:
      tags:
      - user
      operationId: user-option-controller-test/put-user-option
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/user-option-id750575326"
            examples:
              user-option-controller-test/put-user-option:
                value: "{\"todayReviewWords\":200,\"todayStudyWords\":200,\"id\":1,\"\
                  languageCode\":\"en\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/user-option-id750575326"
              examples:
                user-option-controller-test/put-user-option:
                  value: "{\"id\":1,\"todayStudyWords\":200,\"todayReviewWords\":200,\"\
                    languageCode\":\"en\"}"
  /user/option/{id}:
    get:
      tags:
      - user
      operationId: user-option-controller-test/get-user-option
      parameters:
      - name: id
        in: path
        description: option을 보고자 하는 user의 id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/user-option-id750575326"
              examples:
                user-option-controller-test/get-user-option:
                  value: "{\"id\":1,\"todayStudyWords\":200,\"todayReviewWords\":200,\"\
                    languageCode\":\"en\"}"
components:
  schemas:
    cards-id-1143663180:
      type: object
      properties:
        lapses:
          type: number
          description: Again을 누른 횟수
        reps:
          type: number
          description: 총 복습횟수
        scheduledDays:
          type: number
          description: 현재 복습 간격
        lastReview:
          type: string
          description: 마지막으로 복습한 날짜
        nextStudyDate:
          type: string
          description: 다음 학습할 날짜
        state:
          type: string
          description: 카드의 현재 상태
        stability:
          type: number
          description: 기억의 안정도
    user-option-id750575326:
      type: object
      properties:
        todayReviewWords:
          type: number
          description: 오늘 복습할 단어 수
        todayStudyWords:
          type: number
          description: 오늘 공부할 단어 수
        id:
          type: number
          description: user의 고유번호
        languageCode:
          type: string
          description: 어떤 언어로 학습할지 그 언어코드
    cards-id-211271039:
      type: object
      properties:
        reps:
          type: number
          description: 총 복습횟수
        languageCode:
          type: string
          description: 언어코드 (ISO 639-1)
        foreignWord:
          type: string
          description: 외국어 단어
        lapses:
          type: number
          description: Again을 누른 횟수
        difficulty:
          type: string
          description: "언어의 난이도 (easy, normal, hard)"
        scheduledDays:
          type: number
          description: 현재 복습 간격
        cardId:
          type: number
          description: 단어카드의 고유번호
        lastReview:
          type: string
          description: 마지막으로 복습한 날짜
        nextStudyDate:
          type: string
          description: 다음 학습할 날짜
        koreanWord:
          type: string
          description: 한국어 단어
        userCardId:
          type: number
          description: userCard의 고유번호
        state:
          type: string
          description: 카드의 현재 상태
        stability:
          type: number
          description: 기억의 안정도
    cards:
      title: cards
      type: object
      properties:
        size:
          type: number
          description: content의 크기
        pageSize:
          type: number
          description: 전체 페이지의 크기
        page:
          type: number
          description: 현재 페이지의 번호
        content:
          type: array
          description: 실제 데이터들
          items:
            type: object
            properties:
              difficulty:
                type: string
                description: "언어의 난이도 (easy, normal, hard)"
              cardId:
                type: number
                description: 단어카드의 고유번호
              koreanWord:
                type: string
                description: 한국어 단어
              languageCode:
                type: string
                description: 언어코드 (ISO 639-1)
              foreignWord:
                type: string
                description: 외국어 단어
    decks:
      title: decks
      type: object
      properties:
        size:
          type: number
          description: content의 크기
        content:
          type: array
          description: 실제 데이터들
          items:
            type: object
            properties:
              cardCounts:
                type: number
                description: 덱에 포함된 카드 개수
              languageCode:
                type: string
                description: 언어코드
              category:
                type: string
                description: 카드 분류
