spring:
  config:
    import:
      - optional:classpath:/yaml/application-local.yml
      - optional:classpath:/yaml/application-test.yml
      - classpath:/yaml/application-prod.yml

  profiles:
    active: prod

server:
  port: 7070

logging:
  level:
    root: INFO
