spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CL_ID}
            client-secret: ${GOOGLE_CL_SECRET}
            redirect-uri: http://localhost:7070/api/auth/oauth2/success/google
            scope:
              - email
              - profile
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  sql:
#    init:
#      mode: always
#      encoding: UTF-8
#      separator: ;;

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

server:
  port: 7070

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kmu.anki.backend.domain