# application-test.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase?useUnicode=true&characterEncoding=UTF-8
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

