create table card_topics (
                             card_topic_id bigint generated by default as identity,
                             korean_card_id bigint,
                             topic_id varchar(255) check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                             primary key (card_topic_id)
);
create table foreign_cards (
                               foreign_card_id bigint generated by default as identity,
                               foreign_meaning TEXT,
                               foreign_word TEXT,
                               korean_card_id bigint,
                               language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','ms','ru','en','ja','fr','es')),
                               primary key (foreign_card_id)
);
create table korean_cards (
                              korean_card_id bigint generated by default as identity,
                              example_usage TEXT,
                              homograph_number varchar(255),
                              inflection varchar(255),
                              korean_word varchar(255),
                              level varchar(255) check (level in ('easy','normal','hard')),
                              original_language varchar(255),
                              parts_of_speech varchar(255),
                              pronunciation varchar(255),
                              related_words TEXT,
                              primary key (korean_card_id)
);
create table topics (
                        topic_id varchar(255) not null check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                        primary key (topic_id)
);
create table user_cards (
                            user_card_id bigint generated by default as identity,
                            difficulty FLOAT DEFAULT 0,
                            due TIMESTAMP DEFAULT now(),
                            korean_card_id bigint,
                            lapses INT DEFAULT 0,
                            last_review timestamp(6),
                            reps INT DEFAULT 0,
                            scheduled_days FLOAT DEFAULT 0,
                            stability FLOAT DEFAULT 0,
                            user_card_state varchar(255) check (user_card_state in ('New','Learning','Review','Relearning')),
                            user_id bigint,
                            primary key (user_card_id)
);
create table users (
                       user_id bigint generated by default as identity,
                       language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','ms','ru','en','ja','fr','es')),
                       today_review_words integer,
                       today_study_words integer,
                       primary key (user_id)
);
create table user_study_history (
                                    user_study_history_id bigint generated by default as identity,
                                    card_level varchar(255) check (card_level in ('easy','normal','hard')),
                                    card_topic varchar(255) check (card_topic in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                                    deck_type varchar(255) check (deck_type in ('level','meaning')),
                                    study_date timestamp(6),
                                    study_type varchar(255) check (study_type in ('study','review')),
                                    user_id bigint,
                                    primary key (user_study_history_id)
);

alter table if exists card_topics
    add constraint FKmthnqhi4arpfpu11oxwslfmub
    foreign key (korean_card_id)
    references korean_cards
    ON DELETE CASCADE
    ON UPDATE CASCADE;
alter table if exists card_topics
    add constraint FKmj0g8beyd1nfiun1b8cb55u4o
    foreign key (topic_id)
    references topics
    ON DELETE CASCADE
    ON UPDATE CASCADE;
alter table if exists foreign_cards
    add constraint FK4ptejxymk7o24ngaom2v2dlhd
    foreign key (korean_card_id)
    references korean_cards
    ON DELETE CASCADE
    ON UPDATE CASCADE;
alter table if exists user_cards
    add constraint FK8tdqr6c2axjwdbmdbptbxe5t7
    foreign key (korean_card_id)
    references korean_cards
    ON DELETE CASCADE
    ON UPDATE CASCADE;
alter table if exists user_cards
    add constraint FK55ime3genywh3rg5yu62hmfvy
    foreign key (user_id)
    references users
    ON DELETE CASCADE
    ON UPDATE CASCADE;
alter table if exists user_study_history
    add constraint FKhur8c6xhxd3q6sqbe1a2w1h9l
    foreign key (user_id)
    references users;

INSERT INTO topics(topic_id) VALUES('CONCEPT'),('ECONOMY'),('SCIENCE'),('TRANSPORT'),('WEATHER'),('NEWS'),('FEELING'),('GRAMMAR_AND_LANGUAGE'),('CULTURE'),('HOSPITAL'),('LIFE'),('LIVING'),('PERSONALITY'),('NUMBER'),('COMMUNICATION'),('TIME'),('FOOD'),('RELATIONSHIPS'),('NATURE'),('POLITICS'),('RELIGION'),('WORK'),('HOME'),('FASHION_AND_APPEARANCE'),('SCHOOL'),('ACTION'),('ADMINISTRATION');;

-- full text search
ALTER TABLE foreign_cards
    ADD COLUMN foreign_word_vector TSVECTOR;

CREATE INDEX idx_foreign_word_vector ON foreign_cards USING GIN(foreign_word_vector);

CREATE EXTENSION IF NOT EXISTS plpgsql;
CREATE EXTENSION pg_trgm;

CREATE OR REPLACE FUNCTION update_foreign_word_vector()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.language_code = 'en' THEN
          NEW.foreign_word_vector := to_tsvector('english', NEW.foreign_word);
    ELSIF NEW.language_code = 'ar' THEN
          NEW.foreign_word_vector := to_tsvector('arabic', NEW.foreign_word);
    ELSIF NEW.language_code = 'ms' THEN
          NEW.foreign_word_vector := to_tsvector('indonesian', NEW.foreign_word);
    ELSIF NEW.language_code = 'ru' THEN
          NEW.foreign_word_vector := to_tsvector('russian', NEW.foreign_word);
    ELSIF NEW.language_code = 'fr' THEN
          NEW.foreign_word_vector := to_tsvector('french', NEW.foreign_word);
    ELSIF NEW.language_code = 'es' THEN
          NEW.foreign_word_vector := to_tsvector('spanish', NEW.foreign_word);
    ELSE
       NEW.foreign_word_vector := to_tsvector('simple', NEW.foreign_word);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;;

CREATE TRIGGER trg_update_foreign_word_vector
BEFORE INSERT OR UPDATE
ON foreign_cards
FOR EACH ROW
EXECUTE FUNCTION update_foreign_word_vector();
