create table korean_cards (
                              korean_card_id bigint generated by default as identity,
                              example_usage TEXT,
                              homograph_number varchar(255),
                              inflection varchar(255),
                              korean_word varchar(255),
                              level varchar(255) check (level in ('easy','normal','hard')),
                              original_language varchar(255),
                              parts_of_speech varchar(255),
                              pronunciation varchar(255),
                              related_words TEXT,
                              primary key (korean_card_id)
);
create table topics (
                        topic_id varchar(255) not null check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                        primary key (topic_id)
);
create table users (
                       today_review_words integer,
                       today_study_words integer,
                       user_id bigint generated by default as identity,
                       email varchar(255),
                       language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','id','ru','en','ja','fr','es')),
                       login_id varchar(255) unique,
                       login_pwd varchar(255),
                       name varchar(255),
                       role varchar(255) check (role in ('GUEST','USER','ADMIN')),
                       primary key (user_id)
);
create table card_topics (
    card_topic_id bigint generated by default as identity,
    korean_card_id bigint,
    topic_id varchar(255) check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
    primary key (card_topic_id),
    constraint fk_card_topics_korean_card_id foreign key (korean_card_id) references korean_cards,
    constraint fk_card_topics_topic_id foreign key (topic_id) references topics
);
create table foreign_cards (
    foreign_card_id bigint generated by default as identity,
    korean_card_id bigint,
    foreign_meaning TEXT,
    foreign_word TEXT,
    language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','id','ru','en','ja','fr','es')),
    primary key (foreign_card_id),
    constraint fk_foreign_cards_korean_card_id foreign key (korean_card_id) references korean_cards
);
create table user_cards (
    difficulty FLOAT DEFAULT 0,
    lapses INT DEFAULT 0,
    reps INT DEFAULT 0,
    scheduled_days FLOAT DEFAULT 0,
    stability FLOAT DEFAULT 0,
    due TIMESTAMP DEFAULT now(),
    korean_card_id bigint,
    last_review timestamp(6),
    user_card_id bigint generated by default as identity,
    user_id bigint,
    user_card_state varchar(255) check (user_card_state in ('New','Learning','Review','Relearning')),
    primary key (user_card_id),
    constraint fk_user_cards_korean_card_id foreign key (korean_card_id) references korean_cards,
    constraint fk_user_cards_user_id foreign key (user_id) references users
);
create table user_study_history (
    study_date timestamp(6),
    user_id bigint,
    user_study_history_id bigint generated by default as identity,
    card_level varchar(255) check (card_level in ('easy','normal','hard')),
    card_topic varchar(255) check (card_topic in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
    deck_type varchar(255) check (deck_type in ('level','meaning')),
    study_type varchar(255) check (study_type in ('study','review')),
    primary key (user_study_history_id),
    constraint fk_user_study_history foreign key (user_id) references users
);
INSERT INTO topics(topic_id) VALUES('CONCEPT'),('ECONOMY'),('SCIENCE'),('TRANSPORT'),('WEATHER'),('NEWS'),('FEELING'),('GRAMMAR_AND_LANGUAGE'),('CULTURE'),('HOSPITAL'),('LIFE'),('LIVING'),('PERSONALITY'),('NUMBER'),('COMMUNICATION'),('TIME'),('FOOD'),('RELATIONSHIPS'),('NATURE'),('POLITICS'),('RELIGION'),('WORK'),('HOME'),('FASHION_AND_APPEARANCE'),('SCHOOL'),('ACTION'),('ADMINISTRATION');

CREATE EXTENSION IF NOT EXISTS pg_bigm;
CREATE INDEX idx_foreign_word_bigm ON foreign_cards USING gin(foreign_word gin_bigm_ops);
CREATE INDEX idx_korean_word_bigm ON korean_cards USING gin(korean_word gin_bigm_ops);