create sequence korean_meanings_seq start with 1 increment by 50;
create table card_topics (
                             card_topic_id bigint generated by default as identity,
                             korean_card_id bigint,
                             topic_id varchar(255) check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                             primary key (card_topic_id)
);
create table foreign_cards (
                               foreign_card_id bigint generated by default as identity,
                               korean_meaning_id bigint,
                               foreign_meaning TEXT,
                               foreign_word TEXT,
                               language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','id','ru','en','ja','fr','es')),
                               primary key (foreign_card_id)
);
create table korean_cards (
                              korean_card_id bigint generated by default as identity,
                              homograph_number varchar(255),
                              korean_word varchar(255),
                              level varchar(255) check (level in ('easy','normal','hard')),
                              primary key (korean_card_id)
);
create table korean_meanings (
                                 korean_card_id bigint,
                                 korean_meaning_id bigint not null,
                                 example_usage TEXT,
                                 inflection varchar(255),
                                 original_language varchar(255),
                                 parts_of_speech varchar(255),
                                 pronunciation varchar(255),
                                 related_words TEXT,
                                 primary key (korean_meaning_id)
);
create table topics (
                        topic_id varchar(255) not null check (topic_id in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                        primary key (topic_id)
);
create table user_cards (
                            difficulty FLOAT DEFAULT 0,
                            lapses INT DEFAULT 0,
                            reps INT DEFAULT 0,
                            scheduled_days FLOAT DEFAULT 0,
                            stability FLOAT DEFAULT 0,
                            user_card_state_priority integer,
                            due TIMESTAMP DEFAULT now(),
                            korean_card_id bigint,
                            last_review timestamp(6),
                            user_card_id bigint generated by default as identity,
                            user_id bigint,
                            user_card_state varchar(255) check (user_card_state in ('New','Learning','Review','Relearning')),
                            primary key (user_card_id)
);
create table users (
                       daily_review_words integer,
                       daily_study_words integer,
                       utc_offset INTEGER DEFAULT 0,
                       user_id bigint generated by default as identity,
                       email varchar(255),
                       language_code varchar(255) check (language_code in ('mn','ar','zh','vi','th','id','ru','en','ja','fr','es')),
                       login_id varchar(255) unique,
                       login_pwd varchar(255),
                       name varchar(255),
                       role varchar(255) check (role in ('GUEST','USER','ADMIN','AUTHENTICAITON','REFRESH')),
                       primary key (user_id)
);
create table user_study_history (
                                    study_date timestamp(6),
                                    user_id bigint,
                                    user_study_history_id bigint generated by default as identity,
                                    card_level varchar(255) check (card_level in ('easy','normal','hard')),
                                    card_topic varchar(255) check (card_topic in ('CONCEPT','ECONOMY','SCIENCE','TRANSPORT','WEATHER','NEWS','FEELING','GRAMMAR_AND_LANGUAGE','CULTURE','HOSPITAL','LIFE','LIVING','PERSONALITY','NUMBER','COMMUNICATION','TIME','FOOD','RELATIONSHIPS','NATURE','POLITICS','RELIGION','WORK','HOME','FASHION_AND_APPEARANCE','SCHOOL','ACTION','ADMINISTRATION')),
                                    deck_type varchar(255) check (deck_type in ('level','meaning')),
                                    study_type varchar(255) check (study_type in ('study','review')),
                                    primary key (user_study_history_id)
);
alter table if exists card_topics
    add constraint FKmthnqhi4arpfpu11oxwslfmub
    foreign key (korean_card_id)
    references korean_cards;
alter table if exists card_topics
    add constraint FKmj0g8beyd1nfiun1b8cb55u4o
    foreign key (topic_id)
    references topics;
alter table if exists foreign_cards
    add constraint FK674fs70wlmrvjgh4vd7hp3ej4
    foreign key (korean_meaning_id)
    references korean_meanings;
alter table if exists korean_meanings
    add constraint FKsh8049m4s6my93in6qnyivwgq
    foreign key (korean_card_id)
    references korean_cards;
alter table if exists user_cards
    add constraint FK8tdqr6c2axjwdbmdbptbxe5t7
    foreign key (korean_card_id)
    references korean_cards;
alter table if exists user_cards
    add constraint FK55ime3genywh3rg5yu62hmfvy
    foreign key (user_id)
    references users;
alter table if exists user_study_history
    add constraint FKhur8c6xhxd3q6sqbe1a2w1h9l
    foreign key (user_id)
    references users;
